remote-theme: wowthemesnet/mundana-theme-jekyll
# Site
name: "Ella's Story"
description: 'Stories told by Stella'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.svg'
url: 'https://hyesulim.github.io'
baseurl: ''
disqus: 'demowebsite'
email: 'hyesulim.hs@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    stella:
      name:           Stella
      site:           https://sites.google.com/view/hyesulim
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Stella Hyesu Lim, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          hyesulim.hs@gmail.com
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
